### ISSUE TITLE
function throws error

### ISSUE THREAD

**Issue by surrealroad** [connorlacombe/Safari-Push-Notifications#1]
The function `apache_request_headers()` throws an error (function already exists), but the script works if I comment it out

**Comment by connorlacombe** [comment]
Some PHP/Apache installs already have this function. I didn't on my server so I had to use a custom PHP function to emulate it's functionality.

**Comment by surrealroad** [comment]
I've sent a pull request to address this if you want

https://github.com/connorlacombe/Safari-Push-Notifications/pull/2
