### ISSUE TITLE
No notifications appear

### ISSUE THREAD

**Issue by surrealroad** [connorlacombe/Safari-Push-Notifications#3]
I'm having an issue that I can't track down.
What's working:
Safari correctly prompts to enable notifications from the host site
The push service correctly logs the device id to mysql, and removes it as needed
So arguably the trickiest part is all ok.
I've checked that your own test site is working for me perfectly.

I've modified your code to push data to all devices, rather than by id. Again this seems to be ok.
Triggering a push notification however is not working.
I've verified that the server is able to talk to the APNS server with 
`openssl s_client -connect gateway.push.apple.com:2195 -CAfile apns-cert.pem`
No errors are returned by stream_socket_client
I've dumped the output of the json data sent, and it looks ok:

`"{"aps":{"alert":{"title":"Test notification","body":"This is a test push notification","action":"View"},"url-args":[""]}}"`

Not sure what else to check

**Comment by connorlacombe** [comment]
I don't think url-args can be blank. Don't pass it unless there's a valid value.

**Comment by surrealroad** [comment]
I tried with and without an argument, it didn't seem to make any difference. Also I note that even without my changes to the code (i.e. attempting to use your index.php), it doesn't send notifications. For reference, my push service site is http://push.ctrlcmdesc.com but I don't think that'll show anything helpful.

Two things I'm currently unclear on:
1. How exactly should I generate the apns-cert.pem file? I've made mine by running a command on the certificate from Apple that I referenced in the createPushPackage.php file:
`openssl pkcs12 -in WebsitePushCertificate.p12 -out apns-cert.pem -nodes -clcerts` but maybe that's not right. Apple's documentation makes a vague reference to this file: https://www.entrust.net/downloads/binary/entrust_2048_ca.cer but doesn't say where/how it should be used and I didn't see any reference to this file in your code.
2. Do I need to send the push notification from the same server that creates the push package, or can I send it from anywhere as long as I have the .pem and the device ID?

**Comment by connorlacombe** [comment]
This is a good tutorial to generate your certificate (it was made for iOS but it works for Safari as well): http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1

I didn't have to use that entrust certificate however.

You should be generating a signature for your push package using your .p12 certificate (in the createPushPackage.php file), then send your .pem certificate when you connect to Apple's push server. If you aren't getting any errors when you establish a connection with APNS then your .pem is okay. Make sure that you're referencing WebsitePushCertificate.p12 in createPushPackage.php where it has the line:

$certificate_path = "apns-cert.p12"; //Replace with WebsitePushCertificate.p12 and make sure it's in the proper directory.

**Comment by surrealroad** [comment]
During the push registration process I received two files, the p12 and a website_aps_production.cer file. Apple calls this last one a "Website Push ID Production Certificate", and it seems this is something different from the p12 file used for createPushPackage.

The createPushPackage.php script uses the p12, whereas the index.php (specifically, /v1/push) should use the .cer file, converted into a .pem using this command:
`openssl x509 -in website_aps_production.cer -inform der -out apns-cert.pem -nodes -clcerts`

I've uploaded this file but I still don't receive push notifications. I've double-checked the desktop.php file settings are correct for my site, but still nothing. At this point I have to assume there's something about my version of Linux or PHP which is wrong

**Comment by surrealroad** [comment]
One other thing springs to mind. How should the mysql database be formatted?

**Comment by surrealroad** [comment]
Got it. I was truncating the device id.
For reference, the device ID is at least 65 characters long.
